---
- hosts: dns
  tasks:
    - name: Install DNSmasq
      apt:
        name:
          - dnsmasq
    
    - name: Configure DNSmasq
      template:
        src: "templates/dnsmasq.conf.j2"
        dest: "/etc/dnsmasq.conf"

    - name: Restart DNSmasq service
      service:
        name: dnsmasq
        state: restarted
        enabled: true